theme: jekyll-theme-minimal
name: Shi Shan
markdown: kramdown
title: Shi Shan Foo
description: Full Stack, Cloud, AI and Cats
logo: "assets/img/cat.png"
permalink: /:categories/:year/:month/:day/:title:output_ext
